apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: mattermost-issuer
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: obakinolugbade@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: mattermost-priv
    # Enable the HTTP-01 challenge provider
    solvers:
    - selector:
        dnsNames:
          - "matter.devopsnetwork.net"
      dns01:
        route53:
          region: us-west-2
          # The AWS access key ID can be specified using the literal accessKeyID parameter
          # or retrieved from a secret using the accessKeyIDSecretRef
          # If using accessKeyID, omit the accessKeyIDSecretRef parameter and vice-versa
          hostedZoneID: Z00777903RWLGIFSJQB59
          accessKeyIDSecretRef:
            name: konoha
            key: access-key-id
          secretAccessKeySecretRef:
            name: konoha
            key: secret-access-key
